language: java
jdk: oraclejdk7
before_install:
- chmod +x gradlew
before_deploy:
- chmod ugo+x deploy.sh
script:
- bash ./gradlew clean war copyWar zipStatic
- bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/garystafford/spring-music.git
  - secure: a9vmysUsyHe85ojVqc5+3Qq0o0z1lSwdAaUW2cFri9N4dhU73v/u4DJ9DFTJmzORpeH+QOpbnamJo+9GfHTkYNvcOqb72h2k8KUXLNdKM6zhpau5RcBcvNPYFRAap+O7/r2Rn+YrEtkk5IKF6MrE2msP5ot3f3uX7qtpOcQXkGQCLRQe39tG7zVYNy1RWTHMKJX0DLRpIVo0B//8x/vdI3PnNYSin/ijuC6kv94rcHrtomvM1DiRJvoSdgzRWjIPM6sMgu130rPxN1oxv2gJ+H78eOXSh1bj5Z2dVtC9G5863086zcQmmvWF8jluE6b9Ji7rFnyvpOLZjaAq9VK5iafqmE1g2m45XlgMTId92PIgH9BTd3C3w4JnlT6Y7sE5TzoyDIVLjWARAZlU8XFS/uNIXD4gFYdT0CcsPU8HZIqt4/eMCSMLk6mPfBeXWs3gqRSNZg8JZ7hdAVnYTq6ZZir1UZnQe+9JCmAxqmdSmEmG5ocFLpseyR1fgxPTvXisyWDwDm1TQ0rU3MhdI/A4oR3OiTGwzG9Yn8MK2Nn4QDvoWDYThXLRxRJGiN48FOwf4uWWM1FaNUwULdlAH6V602pi1OJ/Fi9D2TZIHxhWDcTXj5wfBWWpSRZM4Y4iq/A/6Un8gG38AcCAW3yqbqcrSGcOMCt1jAE/RMkpFbByi4g=
